- build: examples/simple-24LC01-RK
  photon: [0.6.3, 0.7.0, 0.8.0-rc.8, 1.1.0]
  p1: [latest]
  electron: [latest]
  argon: [0.8.0-rc.27, 0.9.0, latest]
  boron: [latest]
  xenon: [latest]
- build: examples/selftest-24LC01-RK
  photon: [latest]
  argon: [latest]
  
